### ISSUE TITLE
States not updating in Homekit if changed in HA

### ISSUE THREAD

**Issue by kolossboss** [hassio-addons/addon-homebridge#17]
## Problem/Motivation

 If I turn on a switch (or similar) in the HA UI, the status did not change in home.app on my iOS device.
If I restart homebridge I get ONE single update to all stats
Nothing in the logs.

## Expected behavior

 Always update the status in homekit if changed in UI.

## Actual behavior

 Status did not change.

## Steps to reproduce

 (How can someone else make/see it happen)

**Comment by ASchneiderBR** [comment]
Hello guys.

I am not an expert but I also think my homebridge is presenting the same issue. 

Here is a video demonstrating: https://photos.app.goo.gl/6EOHfY1Em0WDc9Yd2

I hope it helps in any way.

Thanks!

**Comment by frenck** [comment]
This seems like a configuration issue. Did you change the URL and/or password in the Homebridge configuration?

**Comment by ASchneiderBR** [comment]
Hello @frenck! Nice to see you here again!

Since I am also having those problems (recorded a video), I tough that I can answer this question.

No, I have not changed my config.

Here it is:

```
{
  "bridge": {
    "name": "Home Assistant",
    "username": "B0:70:2D:8F:18:8F",
    "port": 51826,
    "pin": "123-45-123"
  },
  "description": "Homebridge for Home Assistant",
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "https://MYPUBLICDNS:8123",
      "password": "PASS",
      "default_visibility": "visible",
      "supported_types": [
        "binary_sensor",
        "cover",
        "climate",
        "input_boolean",
        "light",
        "alarm_control_panel",
        "lock",
        "scene",
        "sensor",
        "switch"
      ],
      "logging": false,
      "verify_ssl": false
    }
  ]
}

```
I just cannot set it to work with the docker or local IP, it only updates when my public DNS is set.

I am also receiving this errors on log, it might have something to do with:

```
2017-10-11 21:34:02 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 500, in log
    for key, value in fmt_info:
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 483, in <genexpr>
    return ((key, method(args)) for key, method in self._methods)
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 436, in _format_a
    peername = args[3].get_extra_info('peername')
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 547, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2017-10-11 21:41:15 ERROR (MainThread) [homeassistant.helpers.service] Template rendered invalid service: 
2017-10-11 21:41:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 181, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1025, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/notify/__init__.py", line 143, in async_notify_message
    yield from notify_service.async_send_message(**kwargs)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/notify/webostv.py", line 70, in send_message
    self._client.send_message(message, icon_path=icon_path)
  File "/usr/lib/python3.6/site-packages/pylgtv/webos_client.py", line 214, in send_message
    'iconExtension': icon_extension
  File "/usr/lib/python3.6/site-packages/pylgtv/webos_client.py", line 199, in request
    self.command('request', uri, payload)
  File "/usr/lib/python3.6/site-packages/pylgtv/webos_client.py", line 193, in command
    loop.run_until_complete(asyncio.wait_for(self._command(message), self.timeout_connect, loop=loop))
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25633)
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 356, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
Thank you very much for your time!

**Comment by frenck** [comment]
@tatunts I was never gone ;)
I saw this in your configuration: `https://MYPUBLICDNS:8123`
This should be: `http://172.17.0.1:8123`, without a password.

**Comment by ASchneiderBR** [comment]
Thanks @frenck! 

I had the host set to that IP and removed the password line, now I get this errors:

```
starting version 3.2.2
[ADD-ON] Ensuring old PID files are absent
[ADD-ON] Ensuring D-Bus unique ID exists
[ADD-ON] Starting D-Bus daemon
[ADD-ON] Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.
New relevant interface hassio.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.2.80.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::d82a:bdff:fea7:d295 on vethe9298f4.*.
Registering new address record for fe80::4804:e4ff:fed1:a6ad on veth644559f.*.
Registering new address record for fe80::2cbf:5ff:fe2d:1686 on vetha5dfacb.*.
Registering new address record for fe80::1878:5cff:fece:3de2 on vethfb35452.*.
Registering new address record for fe80::42:71ff:fe56:910a on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::42:58ff:fef3:1823 on hassio.*.
Registering new address record for 172.30.32.1 on hassio.IPv4.
Registering new address record for fe80::db2b:668:ff22:1861 on eth0.*.
Registering new address record for 192.168.2.80 on eth0.IPv4.
Server startup complete. Host name is hassio.local. Local service cookie is 2642084174.
[ADD-ON] Applying HAP NodeJS IPV6 HOTFIX
patching file /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js
[ADD-ON] Starting Homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/12/2017, 4:39:23 PM] Loaded plugin: homebridge-homeassistant
[10/12/2017, 4:39:23 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/12/2017, 4:39:23 PM] ---
[10/12/2017, 4:39:23 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/12/2017, 4:39:23 PM] ---
[10/12/2017, 4:39:23 PM] Loading 1 platforms...
[10/12/2017, 4:39:23 PM] [HomeAssistant] Initializing HomeAssistant platform...
[10/12/2017, 4:39:23 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/12/2017, 4:39:23 PM] [HomeAssistant] Failed getting devices: Error: socket hang up. Retrying...
[10/12/2017, 4:39:28 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/12/2017, 4:39:28 PM] [HomeAssistant] Failed getting devices: Error: socket hang up. Retrying...
[10/12/2017, 4:39:33 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/12/2017, 4:39:34 PM] [HomeAssistant] Failed getting devices: Error: socket hang up. Retrying...
```

**Comment by frenck** [comment]
OK, that is kinda unexpected.
Could you describe your setup to me? Like what type of installation, any special Docker things going on?

**Comment by ASchneiderBR** [comment]
Sorry my friend! I've copied and pasted from your last comment and it did not had the HTTPS hehe

I've set it to use https but without luck. The service start and I can control from my Home App but everything I do on the native HA GUI, just like the video, does not update on Home App.

**Comment by ASchneiderBR** [comment]
Here it is again: https://photos.app.goo.gl/POcHZ1IYlmrUAfzA2

**Comment by frenck** [comment]
Thank you, that is helpful.
Could you describe the system you are running on? And the type of installation?

**Comment by ASchneiderBR** [comment]
Yes, sure:

Hass.io on a Raspberry Pi 3B. These are my addons:

![image](https://user-images.githubusercontent.com/25224882/31516248-4f7b25ea-af6e-11e7-879d-2a1326e377a5.png)

My config file:

```
{
  "bridge": {
    "name": "Home Assistant",
    "username": "B0:70:2D:8F:18:8F",
    "port": 51826,
    "pin": "123-45-123"
  },
  "description": "Homebridge for Home Assistant",
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "https://172.17.0.1:8123",
      "default_visibility": "visible",
      "supported_types": [
        "binary_sensor",
        "cover",
        "climate",
        "input_boolean",
        "light",
        "alarm_control_panel",
        "lock",
        "scene",
        "sensor",
        "switch"
      ],
      "logging": false,
      "verify_ssl": false
    }
  ]
}
```

**Comment by frenck** [comment]
Thanks for all this.
I need to do some more digging in order to find the root cause.
Nevertheless, I'm currently in a major rewrite of all add-ons. The change will be big and will hopefully/maybe fix this issue as well.

**Comment by ASchneiderBR** [comment]
Thank you very much @frenck!

I am sorry that I cannot help you on coding... I really need to learn how.

Please let me know if you need any help on testing or anything else.

Thanks again!

**Comment by frenck** [comment]
I've just released version 2.0.0 of the add-on. Maybe check if this fixes this issue magically❓

**Comment by ASchneiderBR** [comment]
Hello @frenck! 

Thanks for your time and congratulations on this great update! Unfortunately the problem persistis...

All changes made on HA GUI does not updates on Home App. Not even shows on the addon log, very odd. 

It looks like Homebridge is not fetching the states on Hassio. This is really frustrating because I have a couple of Android tablets that is being used to control HA over the native GUI so all commands made on those devices does not update on Home App. Another problem is that I have a few automation that turn on and off things when something is switched, so those state changes does not shows up on Home app as well.

On the other hand, if I set the host to the local docker, Home App works very fast on 4G, using an iPad Mini as a bridge, very nice indeed! If the DDNS domain is set, sometimes, updating the accessories on Home App over 4G takes more than 30 seconds.

I have no idea what is going on here... Sorry to bother you with that.

Thank you very much!

**Comment by ASchneiderBR** [comment]
Hello @frenck and @kolossboss!

Finally I took the courage and removed Lets Encrypt and HTTPS access from my Hassio Setup.

Now this problem is no more. Everything updates very fast and reliably.

Lets Encrypt was the cause of this issue and many others. I will stop using it from now on.

Thanks for your help!

**Comment by kolossboss** [comment]
With one of the latest releases, its now working for me. Fast and all stats are updating fine. 
I use Lets Encrypt and Duck DNS. No problems anymore.

**Comment by ASchneiderBR** [comment]
Amazing! Too bad I now disabled it haha Thanks!

**Comment by frenck** [comment]
The add-on now supports the internal API.

Use the following host in your Homebridge configuration: `http://hassio/homeassistant` and leave the password empty.

This allows Homebridge to communicate with Home Assistant directly without anything in between and is the default setup for new installations of the add-on as of now.

**Comment by ASchneiderBR** [comment]
Thanks @frenck! Worked like a charm:

```
[2017-10-27 10:49:33] Loaded plugin: homebridge-homeassistant
[2017-10-27 10:49:33] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2017-10-27 10:49:33] ---
[2017-10-27 10:49:33] Loaded config.json with 0 accessories and 1 platforms.
[2017-10-27 10:49:33] ---
[2017-10-27 10:49:33] Loading 1 platforms...
[2017-10-27 10:49:33] [HomeAssistant] Initializing HomeAssistant platform...
[2017-10-27 10:49:34] [HomeAssistant] Fetching HomeAssistant devices.
[2017-10-27 10:49:34] Loading 0 accessories...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Chegando no trabalho'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Saindo do trabalho'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Display ar do quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Display ar da suite'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Display ar da sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Saindo de casa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Chegando em casa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Alarme'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Antonio'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Roberta'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Rua do Trabalho'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Interna do Trabalho'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Casa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'TV da Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Alarme da casa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'TV da Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'TV do Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Temperatura externa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Principal do Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Banheiro da Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Balcão'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Área de Serviço'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Entrada'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Banheiro Social'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Luz da TV da sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Principal da Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Luz da TV da suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Principal da Cozinha'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Corredor'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Toalheiro'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Principal da Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Mesa de Jantar'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Entrada casa'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Banheiro Social'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Banheiro Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Cozinha'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Movimento Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Luz Hub Xiaomi'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Trabalho'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Umidade Suíte'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Temperatura Cozinha'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Umidade Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Umidade Quarto'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Umidade Cozinha'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Iluminação Sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Servidor'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Home Theater sala'...
[2017-10-27 10:49:34] [HomeAssistant] Initializing platform accessory 'Desktop'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 613-20-201 │     
    └────────────┘     
                       
[2017-10-27 10:49:34] Homebridge is running on port 51826.
```

**Comment by frenck** [comment]
Thank I'll go ahead and close this issue.
