### ISSUE TITLE
Won't start; Something went wrong contacting the API

### ISSUE THREAD

**Issue by mmnpkf** [hassio-addons/addon-homebridge#40]
Fresh install of hassio on raspberry pi 3.  Added homebridge add-on and when I start the add-on the log shows:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[03:13:35+0000] ERROR ----> Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
ERROR: Something went wrong contacting the API
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
DEBUG: Detected Avahi interfaces: eth0
ERROR: Something went wrong contacting the API
[cont-init.d] 30-avahi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Not sure what do do to fix?  Help!

> (Why the issue was filed)

Expected the add-on to start.

> (What you expected to happen)

Add-on won't start

> (What actually happened)

Flashed fresh install to SD card for Raspberry Pi.  Installed add-on.  Tried to start add-on.

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by kolossboss** [comment]
Same problem. Before updating to v2.0 everything works fine. Now I have the same error:

`[03:13:35+0000] ERROR ----> Something went wrong contacting the API`

Thats my config.json

```
{
  "bridge": {
    "name": "Home Assistant",
    "username": "B8:27:EB:xx:xx:xx",
    "port": 51826,
    "pin": "853-81-325"
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "https://192.168.2.25:8123",
      "password": "xxxxxxx",
      "verify_ssl": false,
      "default_visibility": "visible",
      "supported_types": [
        "binary_sensor",
        "climate",
        "cover",
        "fan",
        "input_boolean",
        "light",
        "lock",
        "media_player",
        "scene",
        "sensor",
        "switch"
      ],
      "logging": true
    }
  ]
}
```

**Comment by frenck** [comment]
@mmnpkf @kolossboss 
Could you guys please provide some details on the platform you are running?
Like:
- Is is generic linux or are you running Hass.io on pre-compiled image (Raspberry Pi for example).
- What is the version of Home Assistant you are running?
- What is the version of the supervisor you are using?
- What is the version of the Host Control you are using?

Thanks in advance!

**Comment by kolossboss** [comment]
Hi thx for reply

- Hass.io on pre-compiled Raspberry image
- 0.55.0
- 0.72
- 1.1

**Comment by codepilotnl** [comment]
Getting the issue on Hass.io RP3 image

- Home Assistant 0.56
- Supervisor 0.72
- Host OS 1.1

Fresh install of Homebridge no upgrade

**Comment by frenck** [comment]
@kolossboss That was quick! Thanks, that is almost all of the latest and greatest versions, which is odd.

Could you provide me a log using `log_level` set to `trace`?

**Comment by codepilotnl** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[10:27:40+0000] ERROR ----> Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to TRACE
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
TRACE: hass.api.supervisor.ping
TRACE: hass.api.call GET /supervisor/ping
ERROR: Something went wrong contacting the API
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
TRACE: hass.config.has_value: avahi_interfaces
TRACE: hass.jq.has_value: /data/options.json .avahi_interfaces
TRACE: hass.jq: /data/options.json .avahi_interfaces | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
DEBUG: Detected Avahi interfaces: eth0
TRACE: hass.config.has_value: avahi_hostname
TRACE: hass.jq.has_value: /data/options.json .avahi_hostname
TRACE: hass.jq: /data/options.json .avahi_hostname | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
TRACE: hass.api.host.info.hostname
TRACE: hass.api.host.info .hostname
TRACE: hass.api.call GET /host/info false .hostname
ERROR: Something went wrong contacting the API
[cont-init.d] 30-avahi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by kolossboss** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[10:30:16+0000] ERROR ----> Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to TRACE
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
TRACE: hass.api.supervisor.ping
TRACE: hass.api.call GET /supervisor/ping
ERROR: Something went wrong contacting the API
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
TRACE: hass.config.has_value: avahi_interfaces
TRACE: hass.jq.has_value: /data/options.json .avahi_interfaces
TRACE: hass.jq: /data/options.json .avahi_interfaces | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
DEBUG: Detected Avahi interfaces: eth0
TRACE: hass.config.has_value: avahi_hostname
TRACE: hass.jq.has_value: /data/options.json .avahi_hostname
TRACE: hass.jq: /data/options.json .avahi_hostname | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
TRACE: hass.api.host.info.hostname
TRACE: hass.api.host.info .hostname
TRACE: hass.api.call GET /host/info false .hostname
ERROR: Something went wrong contacting the API
[cont-init.d] 30-avahi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by frenck** [comment]
Thanks! 
Those where pretty quick replies.
I currently cannot reproduce the issue locally on any of my systems. I might get back to you guys for some questions and tests to find the root cause of the problem.

**Comment by frenck** [comment]
Could one of you guys execute the following command in the SSH add-on and post the output?

`curl --verbose --write-out '\n%{http_code}' --request GET "http://hassio/supervisor/ping"`

**Comment by kolossboss** [comment]
```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.30.32.2...
* TCP_NODELAY set
* Connected to hassio (172.30.32.2) port 80 (#0)
> GET /supervisor/ping HTTP/1.1
> Host: hassio
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 28
< Date: Sat, 21 Oct 2017 09:41:25 GMT
< Server: Python/3.6 aiohttp/2.2.5
< 
* Connection #0 to host hassio left intact
{"result": "ok", "data": {}}
```

**Comment by frenck** [comment]
Hmmm... that is odd, I'm missing some data in your output.

What I expected to see:

```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.30.32.2...
* TCP_NODELAY set
* Connected to hassio (172.30.32.2) port 80 (#0)
> GET /supervisor/ping HTTP/1.1
> Host: hassio
> User-Agent: curl/7.56.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 28
< Date: Sun, 22 Oct 2017 10:36:14 GMT
< Server: Python/3.6 aiohttp/2.2.5
<
* Connection #0 to host hassio left intact
{"result": "ok", "data": {}}
200#
```

That last line is missing from your output, or is it an copy paste error?

The add-on throws this error when `curl` does not exit correctly, so try this one:

`curl --verbose --write-out '\n%{http_code}' --request GET "http://hassio/supervisor/ping" && echo "\nExit code: $?"`

**Comment by kolossboss** [comment]
Sorry I missed the last line. Now everything
```
core-ssh:~# curl --verbose --write-out '\n%{http_code}' --request GET "http://hassio/supervisor/ping"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.30.32.2...
* TCP_NODELAY set
* Connected to hassio (172.30.32.2) port 80 (#0)
> GET /supervisor/ping HTTP/1.1
> Host: hassio
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 28
< Date: Sat, 21 Oct 2017 09:44:05 GMT
< Server: Python/3.6 aiohttp/2.2.5
< 
* Connection #0 to host hassio left intact
{"result": "ok", "data": {}}
200core-ssh:~# 
```
Second

```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.30.32.2...
* TCP_NODELAY set
* Connected to hassio (172.30.32.2) port 80 (#0)
> GET /supervisor/ping HTTP/1.1
> Host: hassio
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 28
< Date: Sat, 21 Oct 2017 09:44:56 GMT
< Server: Python/3.6 aiohttp/2.2.5
< 
* Connection #0 to host hassio left intact
{"result": "ok", "data": {}}
200\nExit code: 0
core-ssh:~# 
```

**Comment by frenck** [comment]
This makes no sense to me... the command you've just executed it the one that fails in the add-on. 😕 

Sounds lame, but maybe restart the OS? 🤕

**Comment by kolossboss** [comment]
I already restarted the whole pi. But no luck :-(

**Comment by frenck** [comment]
Ok, one thing learned, I need to improve the debug output on the API part to gather more information when the API fails. This will require me to update the base add-on image on which this add-on is build. This will take some time.

For the time being, you could probably workaround this issue by setting the `avahi_hostname` to `hassio`;

```json
{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "hassio",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": []
}
```

When this variable is empty, the add-on will try to find out the name using the API. But giving it the name in the configuration, the API part is skipped.

**Comment by kolossboss** [comment]
Ok thx a lot. 
setting `avahi_hostname` to `hassio` works for me! 👍

**Comment by andyrooo82** [comment]
Sorry I couldn’t provide you with the info to help you troubleshoot I was out and about but setting the hostname to hassio has worked for me too. Thanks for providing this workaround so quickly. 👍🏻

**Comment by frenck** [comment]
@andyrooo82 Don't worry about it 👍

**Comment by rpcaeiro** [comment]
Hi Frenck,
Adding this "avahi_hostname": "hassio", to mine, worked well. Thank you very much.

**Comment by frenck** [comment]
This issue might be related to / fixed in this upstream PR: https://github.com/home-assistant/hassio/pull/230

**Comment by marhoy** [comment]
Even after setting "avahi_hostname", I still get an error, but this time about git not being found.
I'm running the latest hassio.io installation on a Rpi3, with everything updated to latest versions, and my config looks like this:

{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "hassio",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": [
    "homebridge-harmonyhub"
  ]
}

Here's the error log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[16:39:53+0000] ERROR ----> Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
**ERROR: Something went wrong contacting the API**
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
[cont-init.d] 30-avahi.sh: exited 0.
[cont-init.d] 50-config.sh: executing... 
[cont-init.d] 50-config.sh: exited 0.
[cont-init.d] 60-ipv6-hotfix.sh: executing... 
[cont-init.d] 60-ipv6-hotfix.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] 82-user-plugins.sh: executing... 
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/debug failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ENOGIT
**npm ERR! No git binary found in $PATH**
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-22T16_40_10_982Z-debug.log
FATAL: Failed installing plugin homebridge-harmonyhub
[cont-init.d] 82-user-plugins.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment]
@marhoy That is a different issue you are experiencing and is not related to this problem.
Please file a separate issue on the issue tracker so we can keep this discussion clean and on-topic.

**Comment by lifuyi** [comment]
the reason is weird that the pi's name changed to "localhost" for some unknown reasons(I guess the upgrading). either rename the pi's name to  "hassio", or add this "avahi_hostname": "hassio" can solve the issue. Thanks

**Comment by frenck** [comment]
@lifuyi Thank you for your comment, but it is not related to the issue at hand.

**Comment by frenck** [comment]
A potentially related issue with Hass.io has been solved & released.

Could somebody experiencing this issue try to update to Supervisor 0.73 and see if this issue is still present?

https://github.com/home-assistant/hassio/releases/tag/0.73

How to update: Hass.io Panel -> menu top right; Advanced Settings; -> Supervisor; Reload -> Supervisor; Update.

**Comment by kolossboss** [comment]
Now its working fine without adding hassio to the avahi hostname.
Thx a lot

**Comment by frenck** [comment]
Great! Thank you for testing @kolossboss! 🏅 

I will close this issue since the problem has been solved upstream.

**TD; DR;**

This issue is solved in Hass.io. Please upgrade your Supervisor to at least version 0.73.

How to update: Hass.io Panel -> menu top right; Advanced Settings; -> Supervisor; Reload -> Supervisor; Update.
